### ISSUE TITLE
altool error

### ISSUE THREAD

**Issue by igor-lemon** [electron/electron-notarize#15]
Hi! I have the next error during notarization

```
Error: Failed to find request UUID in output:

2019-10-22 04:13:50.995 altool[40274:1946835] *** Error: Unable to validate your application. We are unable to create an authentication session.
```

**Comment by MarshallOfSound** [comment]
@igor-lemon That probably means the credentials you provided were incorrect or invalid

**Comment by igor-lemon** [comment]
Nope, I passed correct params. Very interested that I completed success notarized the app via CLI.

```
xcrun altool --notarize-app
               --primary-bundle-id "com.example.ote.zip"
               --username "AC_USERNAME"
               --password "@keychain:AC_PASSWORD"
               --asc-provider <ProviderShortname>
               --file OvernightTextEditor_11.6.8.zip
```

**Comment by joshuef** [comment]
I'm also seeing this w/ travis. _every time_. We're using env vars, which i've tried both escaped and not. 

The same vars work fine locally. But on travis we're consistently seeing this error: https://travis-ci.com/maidsafe/safe_browser/jobs/248327541#L1814-L1822

```error: Failed to find request UUID in output:

2019-10-22 15:30:40.732 altool[4726:13508] *** Error: Unable to validate your application. We are unable to create an authentication session.

    at /Users/travis/build/maidsafe/safe_browser/node_modules/electron-notarize/src/index.ts:82:13

    at step (/Users/travis/build/maidsafe/safe_browser/node_modules/electron-notarize/lib/index.js:31:23)

    at Object.next (/Users/travis/build/maidsafe/safe_browser/node_modules/electron-notarize/lib/index.js:12:53)

    at fulfilled (/Users/travis/build/maidsafe/safe_browser/node_modules/electron-notarize/lib/index.js:3:58)```

Not sure what else to try here.

**Comment by joshuef** [comment]
That build is on `xcode11.2`

**Comment by JohnTendik** [comment]
We're also seeing this issue on the Bamboo side of things. Same issue. Locally the env vars work fine and the app is successfully notarized, however when the build happens on Bamboo it no longer works and we are shown the same error 

```
error	25-Oct-2019 12:34:57	Error: Failed to find request UUID in output:
error	25-Oct-2019 12:34:57	2019-10-25 12:34:57.188 altool[66977:3177522] *** Error: Unable to validate your application. We are unable to create an authentication session.
```

**Comment by chandika** [comment]
Was having the same issue but it was down to not having an app specific password for the account being used to sign with as the appleId would have 2 factor enabled.

https://support.apple.com/en-us/HT204397

After providing the correct auth, works well with xcode 11.2

**Comment by JohnTendik** [comment]
As an update to my comment above, the issue was solved by fixing a user error 😂 I was setting environment variables in the wrong place.

**Comment by hellais** [comment]
I was running into the same issue. 

I found it useful to debug the root cause to run `xcrun altool --notarize-app` with the `--verbose` flag.

Following that I saw that the last error was actually:

```
2019-11-14 09:27:07.743 altool[40837:10907862] jsonResponse as string = {"result":{"Errors":["Please sign in with an app-specific password. You can create one at appleid.apple.com. (-22910)"],"EnableJWTForAllCalls":false,"RestartClient":false,"ErrorCode":-22910,"ErrorMessage":"Please sign in with an app-specific password. You can create one at appleid.apple.com. (-22910)","Success":false},"id":"2019111492707-580","jsonrpc":"2.0","error":{"message":"Please sign in with an app-specific password. You can create one at appleid.apple.com. (-22910)","code":-22910}}
2019-11-14 09:27:07.776 altool[40837:10907862] Web service call (authenticateForSession) result: {
    EnableJWTForAllCalls = 0;
    ErrorCode = "-22910";
    ErrorMessage = "Please sign in with an app-specific password. You can create one at appleid.appl...";
    Errors =     (
        "Please sign in with an app-specific password. You can create one at appleid.appl..."
    );
    RestartClient = 0;
    Success = 0;
}
```

And as suggested by @chandika the fix was indeed to create an app specific password and use that to login.

**Comment by joshuef** [comment]
FWIW, v0.2.0 works for me on travis now. 👍

**Comment by dboakes** [comment]
I've found myself having this issue now myself. I have been notarizing without issue until as recently as last month. But today, I tried to update my app as normal, and keep getting this error. I already had an app specific password, but I created a new one just in case, added to the keychain, but the same error persists. 

Anyone else found this has cropped again recently?

**Comment by fp07** [comment]
You found an solution @dboakes ?
